server:
    port: 8080
    servlet:
        context-path: /vinhkhanhfoodtour/api

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/vinhkhanhfoodtour"
        username: root2
        password: "012345678910"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

jwt:
    signerKey: "AgAOx4qyAzSy8CqqI4zuNJgm3vozakUHD8JICWkLh1j6AHcIzDfjXeyz1YkG8Amu"



app:
    fe:
        verify: "http://localhost:5173/auth/google/verify-otp"
        login: "http://localhost:5173/login"
    otp:
        max-attempts: 5
        expiration-minutes: 5
    reset-token:
        expiration-minutes: 10

springdoc:
    swagger-ui:
        path: /swagger
    api-docs:
        path: /api-docs
